#!/bin/bash
#SBATCH --job-name=1NN
#SBATCH --partition=small-short
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=96:00:00
#SBATCH --cpus-per-task=16
#SBATCH --output=%x_%j.out

# Load required modules
module load openmpi/5.0.5
module load ucx/1.16.0
module load gcclibs/11.4.1

conda activate FRG_env #in case you need python NOTE THIS ONLY WORKS ON MY lcr23 ACCOUNT

# Suppress UCX warnings for unused environment variables
export UCX_WARN_UNUSED_ENV_VARS=n

# disable hcoll
export OMPI_MCA_coll_hcoll_enable=0

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

export LD_LIBRARY_PATH=/home/lcr23/diverge:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/software/GCCLIBS/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/software/MPI/openmpi-5.0.5/lib:$LD_LIBRARY_PATH
# Run code

nk=20
nkf=5
U=15
mu=5
time ./FRG_1NN_ff4.x $U $mu $nk $nkf > 1NN_ff4_${U}_${mu}_${nk}_${nkf}.out
